spring:
  config:
    activate:
        on-profile: prod
  jpa:
    show_sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/loaddata

application:
  basic:
    user: ${BASIC_USER:test}
    password: ${BASIC_PASSWORD:asdqwe}

google.recaptcha.enabled: false